# render.yaml
services:
  - type: web
    name: comisiones-ventas
    env: dotnet
    dotnetVersion: "8.0"  # Ajusta a la versión de tu <TargetFramework> en .csproj
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/ComisionesVentas.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_CLI_TELEMETRY_OPTOUT
        value: 1
    autoDeploy: true