# render.yaml
services:
  - type: web
    name: comisiones-ventas
    env: dotnet
    dotnetVersion: "8.0"  # Especifica la versión de .NET (ajústala según tu proyecto, por ejemplo, 6.0, 7.0, o 8.0)
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/ComisionesVentas.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_CLI_TELEMETRY_OPTOUT
        value: 1
    autoDeploy: true